name: Update Readme Stats
on:
  schedule:
    - cron: "0 */12 * * *"  # update every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update GitHub Stats
      uses: anuraghazra/github-readme-stats@master
      env:
        PAT_1: ${{ secrets.GH_STATS_TOKEN }}
